name: MavSelectBox
author: dustin
category: Interface
tags: [select, dropdown, utility, UI]
docs: http://maveno.us/library/public/mavselectbox/
demo: http://maveno.us/library/public/mavselectbox/
