name: MavSelectBox
author: Dustin Hansen
category: Interface
tags: [select, dropdown, utility, UI]
docs: http://maveno.us/library/public/mavselectbox/
demo: http://maveno.us/library/public/mavselectbox/
current: 0.5.6
